### ISSUE TITLE
Mistake in Cross Validation for Classification of credit-g data

### ISSUE THREAD

**Issue by gauravkumar37** [Prasham8897/Applied_Machine_Learning#1]
Hi,
In https://github.com/Prasham8897/Applied_Machine_Learning/blob/master/Classification%20%26%20Regression/pds2136_Task1.ipynb `In [21]:`, `preprocess = make_column_transformer((OneHotEncoder(handle_unknown="ignore"), categorical_columns_index))` is being used to preprocess the data without scaling (as compared to scaling in the next cell). However, `make_column_transformer` by default drops columns not specified explicitly. Thus, `remainder='passthrough'` should be specified.

**Comment by Prasham8897** [comment]
Thanks for pointing that out. Will update it.
